[about]
name = "gxk(这是hjj)"
avatar = "https://www.google.com/imgres?q=%E5%A5%B6%E9%BE%99&imgurl=https%3A%2F%2Fq7.itc.cn%2Fq_70%2Fimages03%2F20241026%2F661c467cc8424730bad1876277c8a20f.png&imgrefurl=https%3A%2F%2Fwww.sohu.com%2Fa%2F820675439_398212&docid=OaGLRmVoY-W1aM&tbnid=GzQ4fVRW-quMtM&vet=12ahUKEwiYhZWw-qyQAxUMLPsDHczWNuAQM3oECB0QAA..i&w=240&h=277&hcb=2&ved=2ahUKEwiYhZWw-qyQAxUMLPsDHczWNuAQM3oECB0QAA"
hobbies = [""]
skills = [""]

[social]
github = ""
website = ""