[about]
name = "kuangdaikang"
avatar = "https://zhaoyi-tian.github.io/images/profile.png"
hobbies = ["csgo;sleep"]
skills = ["count strike 2"]

[social]
github = "Zhaoyi-Tian"
website = "zhaoyi-tian.cn"
