[about]
name = "yuhuijun"
avatar = "https://zhaoyi-tian.github.io/images/profile.png"
hobbies = ["cs2,Valorant"]
skills = ["count strike 2 dust2"]

[social]
github = "Zhaoyi-Tian"
website = "zhaoyi-tian.cn"
